2023-10-19 11:25:17,666 INFO    StreamThr :546858 [internal.py:wandb_internal():86] W&B internal server running at pid: 546858, started at: 2023-10-19 11:25:17.665692
2023-10-19 11:25:17,672 DEBUG   HandlerThread:546858 [handler.py:handle_request():144] handle_request: status
2023-10-19 11:25:17,673 INFO    WriterThread:546858 [datastore.py:open_for_write():85] open: /home/Student/s4820129/PatternAnalysis-2023/lesion_segmentation_s4820129/wandb/run-20231019_112517-uytgmkcm/run-uytgmkcm.wandb
2023-10-19 11:25:17,674 DEBUG   SenderThread:546858 [sender.py:send():379] send: header
2023-10-19 11:25:17,674 DEBUG   SenderThread:546858 [sender.py:send():379] send: run
2023-10-19 11:25:22,673 DEBUG   HandlerThread:546858 [handler.py:handle_request():144] handle_request: keepalive
2023-10-19 11:25:27,675 DEBUG   HandlerThread:546858 [handler.py:handle_request():144] handle_request: keepalive
2023-10-19 11:25:32,677 DEBUG   HandlerThread:546858 [handler.py:handle_request():144] handle_request: keepalive
2023-10-19 11:25:37,678 DEBUG   HandlerThread:546858 [handler.py:handle_request():144] handle_request: keepalive
2023-10-19 11:25:42,679 DEBUG   HandlerThread:546858 [handler.py:handle_request():144] handle_request: keepalive
2023-10-19 11:25:47,681 DEBUG   HandlerThread:546858 [handler.py:handle_request():144] handle_request: keepalive
2023-10-19 11:25:52,682 DEBUG   HandlerThread:546858 [handler.py:handle_request():144] handle_request: keepalive
2023-10-19 11:25:57,683 DEBUG   HandlerThread:546858 [handler.py:handle_request():144] handle_request: keepalive
2023-10-19 11:26:02,684 DEBUG   HandlerThread:546858 [handler.py:handle_request():144] handle_request: keepalive
2023-10-19 11:26:07,685 DEBUG   HandlerThread:546858 [handler.py:handle_request():144] handle_request: keepalive
2023-10-19 11:26:12,686 DEBUG   HandlerThread:546858 [handler.py:handle_request():144] handle_request: keepalive
2023-10-19 11:26:17,687 DEBUG   HandlerThread:546858 [handler.py:handle_request():144] handle_request: keepalive
2023-10-19 11:26:21,243 INFO    SenderThread:546858 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/Student/s4820129/miniconda3/envs/cluster_env/lib/python3.11/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/Student/s4820129/miniconda3/envs/cluster_env/lib/python3.11/site-packages/urllib3/connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/home/Student/s4820129/miniconda3/envs/cluster_env/lib/python3.11/http/client.py", line 1378, in getresponse
    response.begin()
  File "/home/Student/s4820129/miniconda3/envs/cluster_env/lib/python3.11/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/home/Student/s4820129/miniconda3/envs/cluster_env/lib/python3.11/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Student/s4820129/miniconda3/envs/cluster_env/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Student/s4820129/miniconda3/envs/cluster_env/lib/python3.11/ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Student/s4820129/miniconda3/envs/cluster_env/lib/python3.11/ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Student/s4820129/miniconda3/envs/cluster_env/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/Student/s4820129/miniconda3/envs/cluster_env/lib/python3.11/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/Student/s4820129/miniconda3/envs/cluster_env/lib/python3.11/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Student/s4820129/miniconda3/envs/cluster_env/lib/python3.11/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/Student/s4820129/miniconda3/envs/cluster_env/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/Student/s4820129/miniconda3/envs/cluster_env/lib/python3.11/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/Student/s4820129/miniconda3/envs/cluster_env/lib/python3.11/site-packages/urllib3/connectionpool.py", line 357, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=20)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Student/s4820129/miniconda3/envs/cluster_env/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Student/s4820129/miniconda3/envs/cluster_env/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 358, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Student/s4820129/miniconda3/envs/cluster_env/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Student/s4820129/miniconda3/envs/cluster_env/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Student/s4820129/miniconda3/envs/cluster_env/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 55, in execute
    request = self.session.post(self.url, **post_args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Student/s4820129/miniconda3/envs/cluster_env/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Student/s4820129/miniconda3/envs/cluster_env/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Student/s4820129/miniconda3/envs/cluster_env/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Student/s4820129/miniconda3/envs/cluster_env/lib/python3.11/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=20)
2023-10-19 11:26:22,688 DEBUG   HandlerThread:546858 [handler.py:handle_request():144] handle_request: keepalive
2023-10-19 11:26:27,689 DEBUG   HandlerThread:546858 [handler.py:handle_request():144] handle_request: keepalive
2023-10-19 11:26:32,690 DEBUG   HandlerThread:546858 [handler.py:handle_request():144] handle_request: keepalive
2023-10-19 11:26:37,691 DEBUG   HandlerThread:546858 [handler.py:handle_request():144] handle_request: keepalive
2023-10-19 11:26:42,692 DEBUG   HandlerThread:546858 [handler.py:handle_request():144] handle_request: keepalive
2023-10-19 11:26:47,693 DEBUG   HandlerThread:546858 [handler.py:handle_request():144] handle_request: cancel
2023-10-19 11:26:47,693 DEBUG   HandlerThread:546858 [handler.py:handle_request():144] handle_request: cancel
2023-10-19 11:26:47,824 DEBUG   HandlerThread:546858 [handler.py:handle_request():144] handle_request: shutdown
2023-10-19 11:26:47,825 INFO    HandlerThread:546858 [handler.py:finish():840] shutting down handler
2023-10-19 11:26:48,693 INFO    WriterThread:546858 [datastore.py:close():294] close: /home/Student/s4820129/PatternAnalysis-2023/lesion_segmentation_s4820129/wandb/run-20231019_112517-uytgmkcm/run-uytgmkcm.wandb
2023-10-19 11:26:51,079 INFO    SenderThread:546858 [dir_watcher.py:__init__():211] watching files in: /home/Student/s4820129/PatternAnalysis-2023/lesion_segmentation_s4820129/wandb/run-20231019_112517-uytgmkcm/files
2023-10-19 11:26:51,079 INFO    SenderThread:546858 [sender.py:_start_run_threads():1121] run started: uytgmkcm with start time 1697678717.670288
2023-10-19 11:26:51,079 INFO    SenderThread:546858 [sender.py:finish():1531] shutting down sender
2023-10-19 11:26:51,079 INFO    SenderThread:546858 [dir_watcher.py:finish():358] shutting down directory watcher
2023-10-19 11:26:52,079 INFO    SenderThread:546858 [dir_watcher.py:finish():388] scan: /home/Student/s4820129/PatternAnalysis-2023/lesion_segmentation_s4820129/wandb/run-20231019_112517-uytgmkcm/files
2023-10-19 11:26:52,080 INFO    SenderThread:546858 [dir_watcher.py:finish():402] scan save: /home/Student/s4820129/PatternAnalysis-2023/lesion_segmentation_s4820129/wandb/run-20231019_112517-uytgmkcm/files/config.yaml config.yaml
2023-10-19 11:26:52,080 INFO    SenderThread:546858 [file_pusher.py:finish():175] shutting down file pusher
2023-10-19 11:26:52,080 INFO    SenderThread:546858 [file_pusher.py:join():181] waiting for file pusher
2023-10-19 11:26:54,470 INFO    wandb-upload_0:546858 [upload_job.py:push():131] Uploaded file /home/Student/s4820129/PatternAnalysis-2023/lesion_segmentation_s4820129/wandb/run-20231019_112517-uytgmkcm/files/config.yaml
2023-10-19 11:26:55,080 INFO    SenderThread:546858 [file_stream.py:finish():594] file stream finish called
2023-10-19 11:26:55,785 INFO    SenderThread:546858 [file_stream.py:finish():598] file stream finish is done
