Traceback (most recent call last):
  File "/home/Student/s4820129/PatternAnalysis-2023/lesion_segmentation_s4820129/train.py", line 36, in <module>
    for _, (image, truth) in train_dataloader:
           ^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)